[package]
name = "Alloy"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.4.2", features = ["full"] }
eyre = "0.6.12"
futures-util = "0.3.31"
tokio = { version = "1.40.0", features = ["full"] }
